### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by MrChaker** [michaeljones/elm-parser#2]
Hello ,
 I'm new to elm , I don't really have much knowledge about it , I'm trying to write a function in rust that takes elm_like content and return the corresponding html

it takes 
|> sometag 
      someattributes
    sometext
and returns
\<sometag someattributes .>sometext</sometag.>

Can this library help me with this ?

**Comment by michaeljones** [comment]
I don't think this project is of any use for anything. Sorry. I wish you luck with your task.
